# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitNegBinData <- function(coeff, count, flag, log_lambda, duration) {
    .Call('_assurance_fitNegBinData', PACKAGE = 'assurance', coeff, count, flag, log_lambda, duration)
}

